### PR TITLE
Refactor putc (Issue #8)

### PR DESCRIPTION
**Pull request by anon766**
#8

### CODE REVIEW

**Comment by kssuraaj28** [comment]
Don't use set_cursor multiple times... It is an I/O instruction. Keep it mostly 'software only' and do set_cursor as late as possible.

**Comment by kssuraaj28** [comment]
It's because I/O takes a longer time to do

**Comment by anon766** [comment]
Doesn't matter I feel, each occurence is separate since each one is contained in a condition

**Comment by kssuraaj28** [comment]
You're calling putc multiple times when you're doing puts. For every character you do set_cursor?

**Comment by anon766** [comment]
Yeah, for every character, that's the only way to deal with real time input, but for printf, I guess I could do something

**Comment by rishichordia** [comment]
@anon766  Instead of using a while loop .... For \n use simple modular arithmetic...

**Pull request closed without merging**
